version: '3.8'
services:
  nginxgateway:
    image: vutiendat3601/beatbuddy-nginxgateway:1.0.0
    ports:
      - 88:80
    # volumes:
      # - ./conf.d/:/etc/nginx/conf.d/
      # - ./script/:/script/
      # - ./entrypoint/entrypoint.sh:/docker-entrypoint.sh
    environment:
      - GATEWAY_PROXY_CONFIG_DIR=/etc/nginx/conf.d
      - GATEWAY_REFRESH_SEC=5
      - GATEWAY_EUREKA_SERVER_URL=http://192.168.0.36:8000/eureka
      - GATEWAY_SERVICES=CATALOG,PLAYLIST
